# Option Seller / Grid Volume Farmer
ops:
  dry_run: true
  state_dir: local_state/option_seller
  log_path: logs/option_seller.log
  tick_seconds: 30

market_selection:
  min_volume_24h: 5000
  max_spread_cents: 4
  mid_price_band: [0.35, 0.65]
  exclude_tags: []
  limit: 20

quoting:
  base_spread_cents: 2
  min_spread_cents: 1
  level_spacing_cents: 1
  levels_per_side: 4
  clip_usdc_top: 100
  clip_usdc_deep: 200
  refresh_seconds: 60

inventory:
  per_market_ev_cap: 500
  flatten_threshold_pct: 0.7
  global_ev_cap: 3500
  maker_only: true
